# Generated by Django 3.1.6 on 2021-04-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_coreuser'),
        ('users', '0003_auto_20210403_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collab_songs',
            field=models.ManyToManyField(blank=True, related_name='collaborating_projects', to='core.Song'),
        ),
    ]
