# Generated by Django 3.1.6 on 2021-04-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_coreuser'),
        ('users', '0004_user_collab_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collab_songs',
            field=models.ManyToManyField(blank=True, related_name='collaborating_songs', to='core.Song'),
        ),
    ]
