# Generated by Django 3.1.6 on 2021-04-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_delete_coreuser'),
        ('users', '0005_auto_20210421_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collab_songs',
            field=models.ManyToManyField(blank=True, related_name='collaborating_users', to='core.Song'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_projects',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='core.Project'),
        ),
    ]
