# Generated by Django 3.1.6 on 2021-06-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210612_1017'),
        ('users', '0006_auto_20210422_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_feature_seen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.featurechangelog'),
        ),
    ]
