# Generated by Django 3.1.6 on 2021-02-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lock',
        ),
    ]
