# Generated by Django 3.1.6 on 2021-02-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210211_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='song',
            name='sync_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
