# Generated by Django 3.1.6 on 2021-02-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210226_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='directory_name',
        ),
        migrations.AddField(
            model_name='song',
            name='directory_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
