# Generated by Django 3.1.6 on 2021-02-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210211_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
