# Generated by Django 3.1.6 on 2021-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20210226_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seafile_uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='last_mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='peaks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
