# Generated by Django 3.1.6 on 2021-02-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210211_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync',
            name='songs',
            field=models.ManyToManyField(to='core.Song'),
        ),
    ]
