# Generated by Django 3.1.6 on 2021-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20210228_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='seafile_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
