# Generated by Django 3.1.6 on 2021-02-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sync_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sync',
        ),
    ]
