# Generated by Django 3.1.6 on 2021-03-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='subscribed_projects',
            field=models.ManyToManyField(related_name='subscribed_projects', to='core.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='sharing',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('invite', 'Invite Only')],
                                   default='invite', max_length=10),
        ),
    ]
