# Generated by Django 3.1.6 on 2021-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20210314_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='shared_with_followers',
            field=models.BooleanField(default=False),
        ),
    ]
