# Generated by Django 3.1.6 on 2021-04-04 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_song_shared_with_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreUser',
        ),
    ]
