# Generated by Django 3.1.6 on 2021-04-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_delete_coreuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='studio_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
