# Generated by Django 3.1.6 on 2021-05-04 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_song_studio_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='studio_hash',
        ),
    ]
