# Generated by Django 3.1.6 on 2021-05-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_remove_song_studio_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url_last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
