# Generated by Django 3.1.6 on 2021-06-03 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_song_url_last_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='seafile_uuid',
        ),
    ]
