# Generated by Django 3.1.6 on 2021-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_auto_20210609_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='album_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
