# Generated by Django 3.1.6 on 2021-06-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
