# Generated by Django 3.1.6 on 2021-06-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='song_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
