# Generated by Django 3.1.6 on 2021-08-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_song_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
