# Generated by Django 3.1.6 on 2021-08-26 02:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0035_comment_parent'),
    ]

    database_operations = [migrations.AlterModelTable('Comment', 'comments_comment'),
                           migrations.AlterModelTable('CommentLike', 'comments_commentlike')]

    state_operations = [migrations.DeleteModel('Comment'), migrations.DeleteModel('CommentLike')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
