# Generated by Django 3.1.6 on 2021-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0036_auto_20210825_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
