# Generated by Django 3.1.6 on 2021-03-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sync', '0002_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='project',
        ),
        migrations.AddField(
            model_name='lock',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lock',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
