# Generated by Django 3.1.6 on 2021-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0005_clientupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='updater',
            field=models.FileField(blank=True, null=True, upload_to='updates/updater/'),
        ),
    ]
