# Generated by Django 3.1.6 on 2021-03-11 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0006_auto_20210307_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientupdate',
            old_name='updater',
            new_name='_updater',
        ),
    ]
