# Generated by Django 3.1.6 on 2021-03-13 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0009_clientconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconfig',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
