# Generated by Django 3.1.6 on 2021-04-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_delete_coreuser'),
        ('sync', '0011_changelogentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelogentry',
            old_name='entry',
            new_name='text',
        ),
        migrations.AddField(
            model_name='changelogentry',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changelogentry',
            name='sync',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.sync'),
        ),
    ]
