# Generated by Django 3.1.6 on 2021-05-07 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0012_auto_20210424_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='sync',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog',
                                    to='sync.sync'),
        ),
    ]
