# Generated by Django 3.1.6 on 2021-06-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0013_auto_20210506_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedClientTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientupdate',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='sync.supportedclienttarget'),
        ),
    ]
