# Generated by Django 3.1.6 on 2021-06-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0014_auto_20210607_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
