# Generated by Django 3.1.6 on 2021-06-10 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0016_supportedclienttarget_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientConfig',
        ),
    ]
