# Generated by Django 3.1.6 on 2021-06-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0017_delete_clientconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedclienttarget',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
