# Generated by Django 3.1.6 on 2021-08-15 01:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_auto_20210814_2129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0019_clientlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
