# Generated by Django 3.1.6 on 2021-08-28 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0020_audiosync'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeatureChangelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('changes', models.TextField()),
            ],
        ),
    ]
