# Generated by Django 3.1.6 on 2021-08-28 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='commentlike',
            table=None,
        ),
    ]
