# Generated by Django 3.1.6 on 2021-09-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0002_auto_20210827_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
