# Generated by Django 3.1.6 on 2021-09-03 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0036_auto_20210825_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DurationField()),
                ('end', models.DurationField()),
                ('name', models.CharField(max_length=50)),
                ('color', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
        ),
    ]
