# Generated by Django 3.1.6 on 2021-09-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0002_auto_20210902_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songregion',
            name='color',
            field=models.CharField(max_length=6),
        ),
    ]
