# Generated by Django 3.1.6 on 2021-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('snippets', '0004_auto_20211011_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='url_last_error',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='url_last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
